// <auto-generated />
using Academy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.Migrations
{
    [DbContext(typeof(AcademyContext))]
    [Migration("20250923181244_AddDisciplineTable")]
    partial class AddDisciplineTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy.Models.Discipline", b =>
                {
                    b.Property<int>("discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("discipline_id"));

                    b.Property<string>("discipline_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number_of_lessons")
                        .HasColumnType("int");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
